### The problem we are dealing with is Cancer Diagnosis. But, we are not going to build a model here. Instead we will try to reduce dimensionality using PCA and explore what happens after appying PCA. 

#### Step 1: Let's download all the libraries needed to perform PCA

In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

#### Step 2: Let's download the dataset

In [2]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

col_names = list(cancer.feature_names)
col_names.append('target')
df = pd.DataFrame(np.c_[cancer.data, cancer.target], columns=col_names)

#### Step 3: Let's split the data to X and Y

In [3]:
X = df.drop('target', axis=1)
y = df.target

##### Since PCA is also a distance based technique, it is better to perform scaling before performing PCA.

#### Step 4: Let's perform scaling before doing PCA

In [4]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#### Step 5: Let's perform PCA by passing a fraction value representing percentage of information to be retrieved

In [5]:
pca = PCA(n_components=.9)
X_percent_pca = pca.fit_transform(X_scaled)

##### Now that we have applied PCA, let's get how many variables it has created and how much information each of the new attribute has captured.

#### Step 6: Fetch the number of new features created and how much information each of the new feature has captured.

In [6]:
pca.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768,
       0.04024522, 0.02250734])

##### By looking at the data, we can say that 7 new features have been created. First one has captured 44.2% of the information, second one has captured 18.9% of the information and so on. Now that we have got the information ratio, let's fetch how much weight each original variable had in each of the new features.

#### Step 7: Let's fetch how much weight each original variable had in each of the new features

In [7]:
pca.components_

array([[ 2.18902444e-01,  1.03724578e-01,  2.27537293e-01,
         2.20994985e-01,  1.42589694e-01,  2.39285354e-01,
         2.58400481e-01,  2.60853758e-01,  1.38166959e-01,
         6.43633464e-02,  2.05978776e-01,  1.74280281e-02,
         2.11325916e-01,  2.02869635e-01,  1.45314521e-02,
         1.70393451e-01,  1.53589790e-01,  1.83417397e-01,
         4.24984216e-02,  1.02568322e-01,  2.27996634e-01,
         1.04469325e-01,  2.36639681e-01,  2.24870533e-01,
         1.27952561e-01,  2.10095880e-01,  2.28767533e-01,
         2.50885971e-01,  1.22904556e-01,  1.31783943e-01],
       [-2.33857132e-01, -5.97060883e-02, -2.15181361e-01,
        -2.31076711e-01,  1.86113023e-01,  1.51891610e-01,
         6.01653628e-02, -3.47675005e-02,  1.90348770e-01,
         3.66575471e-01, -1.05552152e-01,  8.99796818e-02,
        -8.94572342e-02, -1.52292628e-01,  2.04430453e-01,
         2.32715896e-01,  1.97207283e-01,  1.30321560e-01,
         1.83848000e-01,  2.80092027e-01, -2.19866379e-

##### By looking at the data above, we can notice that there are 7 brackets, each bracket specfies one new feature. Fractions within the brackets specify how much weight each of the old feature respectively had on the new feature. For example, in the first PCA feature, weightage of first old feature is 0.21 approximately and so on. So, all of the variables had contribution on each variable created by PCA.

##### Now that we have seen how to perform PCA by passing a fraction value representing percentage of information to be retrieved, let's perform PCA by passing number of features to be retrieved.

#### Step 8: Let's perform PCA by passing number of features to be retrieved

In [8]:
pca_feature = PCA(n_components=10)
X_number_pca = pca_feature.fit_transform(X_scaled)

##### Now that we have applied PCA, let's fetch how much information each of the new attribute has captured.

#### Step 9: Fetch the amount of information each of the new feature has captured.

In [9]:
pca_feature.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768,
       0.04024522, 0.02250734, 0.01588724, 0.01389649, 0.01168978])

##### By looking at the data, we can say that First one has captured 44.2% of the information, second one has captured 18.9% of the information and so on. Now that we have got the information ratio, let's fetch how much weight each original variable had in each of the new features. The amount of information captured by first 7 variables is same as the information captured by variables created above. So, we can say that the way PCA is performed doesn't vary.

#### Step 10: Let's fetch how much weight each original variable had in each of the new features

In [10]:
pca_feature.components_

array([[ 2.18902444e-01,  1.03724578e-01,  2.27537293e-01,
         2.20994985e-01,  1.42589694e-01,  2.39285354e-01,
         2.58400481e-01,  2.60853758e-01,  1.38166959e-01,
         6.43633464e-02,  2.05978776e-01,  1.74280281e-02,
         2.11325916e-01,  2.02869635e-01,  1.45314521e-02,
         1.70393451e-01,  1.53589790e-01,  1.83417397e-01,
         4.24984216e-02,  1.02568322e-01,  2.27996634e-01,
         1.04469325e-01,  2.36639681e-01,  2.24870533e-01,
         1.27952561e-01,  2.10095880e-01,  2.28767533e-01,
         2.50885971e-01,  1.22904556e-01,  1.31783943e-01],
       [-2.33857132e-01, -5.97060883e-02, -2.15181361e-01,
        -2.31076711e-01,  1.86113023e-01,  1.51891610e-01,
         6.01653628e-02, -3.47675005e-02,  1.90348770e-01,
         3.66575471e-01, -1.05552152e-01,  8.99796818e-02,
        -8.94572342e-02, -1.52292628e-01,  2.04430453e-01,
         2.32715896e-01,  1.97207283e-01,  1.30321560e-01,
         1.83848000e-01,  2.80092027e-01, -2.19866379e-